title: Malaviya Mission - Theme ICT 
description: Part of NEP for Higher Ed, this is the content that accompanies the Malaviya Mission ICT sessions
theme: just-the-docs

url: https://rahul101001000.github.io/malaviya-mission-ict

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/rahul101001000/malaviya-mission-ict
